apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: minio
spec:
  containers:
  - name: minio
    image: minio/minio:RELEASE.2020-02-20T22-51-23Z
    args:
      - server
      - /data
    env:
      - name: MINIO_ACCESS_KEY
        value: "breakfast"
      - name: MINIO_SECRET_KEY
        value: "breakfast"
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    app: minio
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
