apiVersion: v1
kind: Pod
metadata:
  name: mongo
  namespace: default
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo:4.2.8
    imagePullPolicy: Always
    ports:
    - name: mongo
      containerPort: 27017
      hostPort: 27017
    env:
    - name: MONGO_INITDB_ROOT_USERNAME
      value: "mongouser"
    - name: MONGO_INITDB_ROOT_PASSWORD
      value: "mongosecret"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: default
  labels:
    app: mongo
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
