apiVersion: v1
kind: Pod
metadata:
  name: object-service
  labels:
    app: object-service
spec:
  containers:
  - name: object-service
    image: jniestroy/object-service:0.2
    imagePullPolicy: Always
    command: ["python3", "main.py"]
    ports:
      - containerPort: 5005
    env:
      - name: MINIO_URL
        value: "http://minio.default:9000"
      - name: MINIO_KEY
        value: "breakfast"
      - name: MINIO_SECRET
        value: "breakfast"
      - name: PYTHONUNBUFFERED
        value: "1"
      - name: ORS_URL
        value: "http://mds.default/"
      - name: AUTH_SERVICE
        value: "http://auth.default"
      - name: OS_SERVICE
        value: "http://object-service/"
      - name: AUTH_KEY
        value: "test secret"
---
apiVersion: v1
kind: Service
metadata:
  name: object-service
  labels:
    app: object-service
spec:
  selector:
    app: object-service
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5005
    protocol: TCP
