apiVersion: v1
kind: Pod
metadata:
  namespace: default
  name: stardog
  labels:
    app: stardog
spec:
  containers:
  - name: stardog
    image: jniestroy/stardog:latest
    env:
    - name: STARDOG_LICENSE_PATH
      value: /opt/mount/stardog-license-key.bin
---
apiVersion: v1
kind: Service
metadata:
    namespace: default
    name: stardog
    labels:
        app: stardog
spec:
  selector:
    app: stardog
  ports:
  - protocol: TCP
    port: 5820
    targetPort: 5820
  type: ClusterIP
