apiVersion: v1
kind: Pod
metadata:
  name: testing-pod
spec:
  containers:
  - name: testing-pod
    image: jniestroy/testing-pod
    command: ["jupyter","notebook","--allow-root","--NotebookApp.token=''","--NotebookApp.password=''", "/Demo"]
